name: Deploy to GitHub Pages

on:
  push:
    branches: [ aster ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Install aster from git
        uses: baptiste0928/cargo-install@v3
        with:
          crate: aster-ssg
          git: https://github.com/Wybxc/aster.git
          commit: fbde4f577f7ef0cd2c173aa20d1f61aad56f8d66
      - name: Build
        run: aster build
      - name: Upload site
        uses: actions/upload-pages-artifact@v4
        with:
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
